### ISSUE TITLE
bgp network can not be valid!!!

### ISSUE THREAD

**Issue by nskeeper** [CumulusNetworks/quagga#1]
1,my linux box topology:
---------------------------------------------------------------------------------------
pc1-----(3.3.3.1/24)linux box1(1.1.1.1/24)----------(1.1.1.2/24)linux box2(2.2.2.2/24)-------pc2

Note that box1 has cumulus quagga version and box2 has official quagga version.

2,on box1, vtysh -d bgpd -c "show running":
---------------------------------------------------------------------------------------
Building configuration...

Current configuration:
!
!
password bgp
!
router bgp 100
 bgp router-id 1.1.1.1
 bgp network import-check
 network 3.3.3.0/24
 neighbor 1.1.1.2 remote-as 100
 neighbor 1.1.1.2 timers 60 180
 neighbor 1.1.1.3 next-hop-self
!
line vty
!
end

3,on box1,vtysh -d bgpd -c "show ip bgp":
---------------------------------------------------------------------------------------
BGP table version is 0, local router ID is 1.1.1.1
Status codes: s suppressed, d damped, h history, * valid, > best, = multipath,
              i internal, r RIB-failure, S Stale, R Removed
Origin codes: i - IGP, e - EGP, ? - incomplete

   Network          Next Hop            Metric LocPrf Weight Path
*>i2.2.2.0/24       1.1.1.2                  0    100      0 i
   3.3.3.0/24       0.0.0.0                  0         32768 i

Total number of prefixes 2

4,on box2,  vtysh -d bgpd -c "show running":
---------------------------------------------------------------------------------------
Building configuration...

Current configuration:
!
!
password ngfw
!
router bgp 100
 bgp router-id 1.1.1.2
 bgp network import-check
 network 2.2.2.0/24
 neighbor 1.1.1.1 remote-as 100
 neighbor 1.1.1.1 timers 60 180
 neighbor 1.1.1.1 next-hop-self
!
line vty
!
end

5,on box2, vtysh -d bgpd -c "show ip bgp":
---------------------------------------------------------------------------------------
BGP table version is 0, local router ID is 1.1.1.2
Status codes: s suppressed, d damped, h history, * valid, > best, = multipath,
              i internal, r RIB-failure, S Stale, R Removed
Origin codes: i - IGP, e - EGP, ? - incomplete

   Network          Next Hop            Metric LocPrf Weight Path
*> 2.2.2.0/24       0.0.0.0                  0         32768 i

Total number of prefixes 1

6,my question is why is 3.3.3.0/24 unvalid  on my box1? 
---------------------------------------------------------------------------------------

**Comment by oleg-umnik** [comment]
Please, show full configuration. Post output of vtysh -c 'sh ru' for each box.

**Comment by dwalton76** [comment]
Hello nskeeper,
I work for cumulus on the routing team.  We have a bug with "bgp network import-check" where it incorrectly thinks the 'network x.x.x.x' routes are invalid.  Can you try removing import-check and see if that clears the issue?  If so then the bug you are hitting is CM-4256.

Thanks,
Daniel

**Comment by nskeeper** [comment]
hello Daniel,
Yes. It is ok when removing import-check.
Thanks,
LiHongguang

**Comment by dwalton76** [comment]
Hi LiHongguang,
CM-4256 is just our internal ticket number, there isn't a way to view it externally.  Probably the easiest way to track when it will be fixed is to open a support ticket with cumulus and they can help keep you in the loop.  We have a fix in code review but it has not been committed yet.

Daniel

**Comment by dwalton76** [comment]
FYI this should be fixed in 2.5.1

**Comment by nskeeper** [comment]
Hi Daniel，
Because I need to finish a bgp test based on your cumulus quagga version, where i can get the patch for that problem.
Thanks,
LiHongguang

**Comment by dwalton76** [comment]
We are going to aim for getting it pushed to the repo here by the end of this weekend at the latest.  We just need to finish code reviewing the patch and testing it.

**Comment by nskeeper** [comment]
Thanks for your feedback , I do appreciate your effort, good work, well done.

**Comment by ddutt** [comment]
I've checked in a fix for making "bgp network import-check" work again. Please pull out the tree again. I've rebased the tree and so a pull will cause merge conflicts. So, please checkout a new tree.

Dinesh

**Comment by nskeeper** [comment]
I have checked out the new tree to test the problem above. I added a 'network x.x.x.x' route that is not directly connected on box1 with default route, then box2 learned it, but cisco router never seem able to do it in this way.

**Comment by ddutt** [comment]
Please use "bgp network import-check" to get the behavior you want. The patch checked in was to fix this as it was broken. Quagga by default announces any prefix configured with network and you need to add the import-check statement to make it only announce prefixes it knows about.

**Comment by nskeeper** [comment]
In my configuration, there is the "bgp network import-check".

**Comment by dwalton76** [comment]
Can you send us the following where x.x.x.x is the prefix you are trying to originate with a network statement?
- show ip bgp x.x.x.x
- show ip route x.x.x.x
- show run

Thanks

**Comment by donaldsharp** [comment]
LiHongguang -

Could you open a support case with this information at
https://cumulusnetworks.com/secure/accounts/login/?next=/support/new-support-request/
?  We would like to be able to support you more fully and to also be able
to track our support load.  Feel free to reference these emails.

thanks!

donald

**Comment by nskeeper** [comment]
Hi donald,

Thanks for your comment. I will open one case at the web link you specify.

Thks & Rgds!
lihongguang

**Comment by nskeeper** [comment]
hi guys,
Please tell me on how i can solve the two problem above.
Thanks,
lihongguang

**Comment by donaldsharp** [comment]
I belive both Daniel and Oleg have asked pertinent questions about
information needed to solve the issue, Neither of which I see answers from
you on.  I would also like to see a restatement of what you think is wrong
since this has been going on for a few weeks.

thanks!

donald

**Comment by nskeeper** [comment]
1. I have the laterest cumulus quagga version installed on my Linux box.
-------------------------------------------------------------------------------------------------------------------------------
2. My first problem is that Cisco router or quagga-0.99.23 with "bgp network import-check" will not announces any prefix "x.x.x.x", not directly connected , even if it is reachable by the default route or recursive lookup nexthop, but why does cumulus quagga do it.

a. At my bash shell prompt, type in "ip route list"
-------------------------------------------------------------------------------------------------------------------------------
default via 10.0.2.2 dev enp0s3 proto static metric 1024 
10.0.0.0/16 dev enp0s3 proto kernel scope link src 10.0.2.252 
192.168.122.0/24 dev virbr0 proto kernel scope link src 192.168.122.1

b. vtysh -d bgpd -c "show running"
---------------------------------------------------------------------------------------------------------------------------
Building configuration...

Current configuration:
!
hostname bgpd
log stdout
!
password zebra
!
router bgp 7675
 bgp router-id 192.168.122.1
 bgp network import-check // make bgp only announce prefixes it knows about
 network 10.0.0.0/16
 network 100.100.100.0/24 // bgp will (wrongly) announce this prefix which it does not know about
!
line vty
!
end

c. vtysh -d bgpd -c "show ip bgp"
---------------------------------------------------------------------------------------------------------------------------
BGP table version is 0, local router ID is 192.168.122.1
Status codes: s suppressed, d damped, h history, * valid, > best, = multipath,
              i internal, r RIB-failure, S Stale, R Removed
Origin codes: i - IGP, e - EGP, ? - incomplete

   Network          Next Hop            Metric LocPrf Weight Path
*> 10.0.0.0/16      0.0.0.0                  0         32768 i
*> 100.100.100.0/24 0.0.0.0                  0         32768 i

d. vtysh -d bgpd -c "show ip bgp 100.100.100.0"
---------------------------------------------------------------------------------------------------------------------------
BGP routing table entry for 100.100.100.0/24
Paths: (1 available, best #1, table Default-IP-Routing-Table)
  Not advertised to any peer
  Local
    0.0.0.0 from 0.0.0.0 (192.168.122.1)
      Origin IGP, metric 0, localpref 100, weight 32768, valid, sourced, local, best
      Last update: Mon Feb  9 10:26:07 2015

e. vtysh -d zebra -c "show ip route 100.100.100.0"
---------------------------------------------------------------------------------------------------------------------------
Routing entry for 0.0.0.0/0
  Known via "kernel", distance 0, metric 1024, best
  * 10.0.2.2, via enp0s3

f. removing the default route, the prefix "100.100.100.0" will be invalid in bgp route table.
---------------------------------------------------------------------------------------------------------------------------
BGP table version is 0, local router ID is 192.168.122.1
Status codes: s suppressed, d damped, h history, * valid, > best, = multipath,
              i internal, r RIB-failure, S Stale, R Removed
Origin codes: i - IGP, e - EGP, ? - incomplete

   Network          Next Hop            Metric LocPrf Weight Path
*> 10.0.0.0/16      0.0.0.0                  0         32768 i
   100.100.100.0/24 0.0.0.0              0         32768 i


3. The second problem
---------------------------------------------------------------------------------------------------------------------------
After issuing the command "killall -9 bgpd",  i restart bgpd daemon(typing in "bgpd -d"), the following is displayed:
2015/02/09 11:31:44 BGP: sendmsg_nexthop: Can't send NH register, Zebra client not established
2015/02/09 11:31:44 BGP: sendmsg_nexthop: Can't send NH register, Zebra client not established
 
Thks & Rgds!
lihongguang

**Comment by nskeeper** [comment]
If there is any further information needed please feel free to tell me.
thanks,
lihongguang

**Comment by ddutt** [comment]
Hi Lihongguang,

No further info is required. I know the reason for your network import
check issue, I think. I've been busy all of last week and so couldn't get
to working on a fix.

Do you mind telling me what your use case is for trying this code ?

Dinesh

**Comment by nskeeper** [comment]
Hi Dinesh,
I think that it is only the basic functional test case.
thanks,
Lihongguang

**Comment by ddutt** [comment]
Hi Lihong,

Please pull the tree again and try. I've pushed out a fix for the import check issue now.

Dinesh

**Comment by ddutt** [comment]
I'm not sure what you mean by bgp recursive nexthop lookup. Can you elaborate further ?

We do support next hop tracking feature that resolves a NH recursively and notifies BGP when it becomes valid. The final route installed in the FIB is also flattened after recursive resolution. 

Dinesh
