### ISSUE TITLE
Metric is not true on PtP interfaces

### ISSUE THREAD

**Issue by HFriebis** [CumulusNetworks/quagga#19]
I connected 12 virtual machines using kvm in a line with pointopint. All interface routes show the metric 20. The OSPF database shows the right metric:
ospfd> show ip ospf route    
============ OSPF network routing table ============
N    10.1.1.1/32           [110] area: 0.0.0.0
                           via 10.11.1.1, eth1.1035
N    10.2.1.1/32           [100] area: 0.0.0.0
                           via 10.11.1.1, eth1.1035
N    10.3.1.1/32           [90] area: 0.0.0.0
                           via 10.11.1.1, eth1.1035
N    10.4.1.1/32           [80] area: 0.0.0.0
                           via 10.11.1.1, eth1.1035
N    10.5.1.1/32           [70] area: 0.0.0.0
                           via 10.11.1.1, eth1.1035
N    10.6.1.1/32           [60] area: 0.0.0.0
                           via 10.11.1.1, eth1.1035
N    10.7.1.1/32           [50] area: 0.0.0.0
                           via 10.11.1.1, eth1.1035
N    10.8.1.1/32           [40] area: 0.0.0.0
                           via 10.11.1.1, eth1.1035
N    10.9.1.1/32           [30] area: 0.0.0.0
                           via 10.11.1.1, eth1.1035
N    10.10.1.1/32          [20] area: 0.0.0.0
                           via 10.11.1.1, eth1.1035
N    10.11.1.1/32          [10] area: 0.0.0.0
                           via 10.11.1.1, eth1.1035
N    10.12.1.1/32          [0] area: 0.0.0.0
                           directly attached to lo
The kernel routes are calculated incorrectly:
10.1.1.1        10.11.1.1       255.255.255.255 UGH   20     0        0 eth1.1035
10.2.1.1        10.11.1.1       255.255.255.255 UGH   20     0        0 eth1.1035
10.3.1.1        10.11.1.1       255.255.255.255 UGH   20     0        0 eth1.1035
10.4.1.1        10.11.1.1       255.255.255.255 UGH   20     0        0 eth1.1035
10.5.1.1        10.11.1.1       255.255.255.255 UGH   20     0        0 eth1.1035
10.6.1.1        10.11.1.1       255.255.255.255 UGH   20     0        0 eth1.1035
10.7.1.1        10.11.1.1       255.255.255.255 UGH   20     0        0 eth1.1035
10.8.1.1        10.11.1.1       255.255.255.255 UGH   20     0        0 eth1.1035
10.9.1.1        10.11.1.1       255.255.255.255 UGH   20     0        0 eth1.1035
10.10.1.1       10.11.1.1       255.255.255.255 UGH   20     0        0 eth1.1035
10.11.1.1       10.11.1.1       255.255.255.255 UGH   20     0        0 eth1.1035

**Comment by donaldsharp** [comment]
The kernel routes are correct.  The metric that could be inserted into the kernel means nothing across protocols and across routing suites.  Additionally the linux kernel has no knowledge of metric and Admin distance, that would be needed to actually hand the 'correct' amount in.  As such we have intentionally choosen a metric of 20.  If a connected or static route is entered by hand from the linux cli, it will be choosen by the kernel, but the chosen value of 20 is big enough if you happen to run multiple routing suites you can do things to choose one routing suite over the other.
