### ISSUE TITLE
mirror of savannah?

### ISSUE THREAD

**Issue by AdrianSimionov** [CumulusNetworks/quagga#5]
If this repository wants to be a mirror of the official one from savannah, you are missing the tags and releases. 

Also, the branches are not kept up to date.

Bellow script should provide a starting point on keeping GitHub fully in sync.

https://github.com/AdrianSimionov/Scripts/blob/master/GitHub.sh

If I am wrong and this is a different repository, please close this issue.

**Comment by donaldsharp** [comment]
We don't.  We just wanted a relatively recent mainline, which is exactly what we want.
