### ISSUE TITLE
bgp macro "PEER_FLAG_FORCE_NEXTHOP_SELF" missing

### ISSUE THREAD

**Issue by nskeeper** [CumulusNetworks/quagga#6]
Hi donald,

Bgp code lack of macro "PEER_FLAG_FORCE_NEXTHOP_SELF" definition in the branch cm_2.5 will lead to compilation errors.

Lihongguang

**Comment by donaldsharp** [comment]
nskeeper -

My apologies for the slow response.  You posted this issue right before I went on vacation and today is the first chance I've had to look at it, since I've gotten back.

I just committed a fix for this issue.  Please let me know if you experience any other issues.

**Comment by nskeeper** [comment]
Another one is that "nexthop self" and "default originate" can not work for "bgp group".

**Comment by nskeeper** [comment]
Hi donald,

Does the problem exist? Is there a solution or a good way to get around it?

BTW, when will cumulus-master branch update?

Thanks!

nskeeper

**Comment by donaldsharp** [comment]
nskeeper -

I need to make an update to the cm_2.5 branch that should fix the nexthop issue.  I plan to do this at the same time that we release the 2.5.4 code.  

donald

**Comment by nskeeper** [comment]
Hi donald,

Thank you for the information. 
I have another question:
what is the difference between the cm_2.5 and cumulus-master branches?
The cumulus-master is not updated for a long time, and there has been a lot of difference with cm_2.5. When will its update arrive? 

Thanks!

nskeeper

**Comment by donaldsharp** [comment]
Yes cumulus-master has not been updated for a long time.  I will not be updating it unless we roll a release off the internal master, which is unlikely.  

The cm_2.5 branch is our current release vehicle, this is where the action will be.  I am not at liberty to discuss release dates.  If you are interested in knowing more please contact your account manager.  They can help you plan around this sort of information.

thanks!

donald
