### ISSUE TITLE
ospf6d may be memory leak!

### ISSUE THREAD

**Issue by nskeeper** [CumulusNetworks/quagga#7]
Hello,

Today i review the code in ospf6_spf.c file, i found that ospf6_vertex_delete doesn't free vertex's nexthop list. Will this result in a memory leak?

Best,
LiHongguang

**Comment by donaldsharp** [comment]
Sure looks like it does.  
Also looks like this is in baseline quagga.  If you code up a fix, I would recommend you submit it to quagga-dev.

thanks!

donald

**Comment by nskeeper** [comment]
Hi donald,

Quagga community is not active and always make slowly response to a push request. I look forward to the next update of cumulus-master and cm_2.5 branch.

thanks!
LiHongguang
