### ISSUE TITLE
make error with ipv6

### ISSUE THREAD

**Issue by vinllen** [CumulusNetworks/quagga#8]
Hi, Dear all,

I use the configure with parameter --disable-ipv6 beacause there is no ipv6 in my kernel, but it'll throw the   error:

zebra_rib.c: In function 'is_zebra_main_routing_table':
zebra_rib.c:225: warning: comparison between signed and unsigned integer expressions
zebra_rib.c: At top level:
zebra_rib.c:232: warning: no previous prototype for '_nexthop_add'
zebra_rib.c: In function 'nexthops_free':
zebra_rib.c:342: error: 'union <anonymous>' has no member named 'prefix6'
zebra_rib.c:342: error: 'union g_addr' has no member named 'ipv6'
zebra_rib.c: In function 'nexthop_active_check':
zebra_rib.c:1273: error: 'union g_addr' has no member named 'ipv6'
zebra_rib.c: In function 'rib_add_ipv4':
zebra_rib.c:2145: warning: comparison between signed and unsigned integer expressions
zebra_rib.c: In function 'rib_delete_ipv4':
zebra_rib.c:2512: warning: comparison between signed and unsigned integer expressions
make64[2]: *** [zebra_rib.o] Error 1
make64[2]: Leaving directory `/home/chenxing/quagga-vrfpatch/zebra'
make64[1]: *** [all-recursive] Error 1
make64[1]: Leaving directory `/home/chenxing/quagga-vrfpatch'
make64: *** [all] Error 2

I have tryed the version of "origin/cumulus-master" and "origin/cm_2.5", but all of them was built failer. Only the version "origin/stable/0.99.23" which was not patched is success.

Could anyone help me ?

**Comment by ddutt** [comment]
Unfortunately, we don't compile without enabling ipv6. I suspect the error you see is just the first of many that'll fail because of lack of IPv6. Quagga mainline has also removed support for this option "disable-ipv6".

Dinesh

**Comment by ddutt** [comment]
Here's the link to the quagga commit that removes support for compiling without ipv6: https://lists.quagga.net/pipermail/quagga-dev/2015-February/012097.html

**Comment by vinllen** [comment]
Hi, Dinesh,

I try to configure without the parameter --disable-ipv6, but it also failed.

There is no ipv6/inet6 in my host, so i cannot pass the compile only if i install it? Do you have any other way to pass the compile ?

**Comment by ddutt** [comment]
Unfortunately not, AFAIK. What device is this without IPv6 ?

**Comment by vinllen** [comment]
Because in our Intranet, we only use ipv4. The host will send ipv6 packet out which was not allowed if i enable ipv6

**Comment by ddutt** [comment]
Sorry, cannot help you here. And like I said, even mainline quagga has removed support for compiling without v6 support. You may need to do some fixing yourself to make this happen i.e. allow disable-ipv6 to work. But that option will be going away soon.

Dinesh

**Comment by vinllen** [comment]
It's ok, thankyou Dinesh

**Comment by vinllen** [comment]
Hi, Dinesh,

I have passed the compile when i change the "#define HAVE_IPV6 1" in the configure to  "#define HAVE_IPV6 0"

I think it's not a perfect way to set static HAVE_IPV6 in configure, the HAVE_IPV6 should be set according to the ipv6 in the kernel moudle.
