### ISSUE TITLE
start two ospfd instances throw error

### ISSUE THREAD

**Issue by vinllen** [CumulusNetworks/quagga#9]
Hi, Dinesh,

Sorry to asking for another question. I install the quagga in my host, and start two ospfd in the following step:

1.create two conf file in the etc directory : ospfd-1.conf ospfd-2.conf
2.cd into the sbin dierctory and start the first ospfd process
sudo ./ospfd -n 1 
It looks like everything works well:
2015/08/07 09:04:17 OSPF[1]: OSPFd 0.99.23 starting: vty@2604, /var/run/quagga/ospfd-1.vty

2.Then i start the second one:
sudo ./ospfd -n 2
The command show:
2015/08/07 09:06:50 OSPF[2]: can't bind socket : Address already in use
2015/08/07 09:06:50 OSPF[2]: can't bind socket
2015/08/07 09:06:50 OSPF[2]: OSPFd 0.99.23 starting: vty@2604, /var/run/quagga/ospfd-2.vty

3.When i check the /var/run/quagga, i found there is only two files in this directory where lack of ospfd-1.vty and ospfd-2.vty:
ospfd-1.pid  ospfd-2.pid

4.Ofcourse i cannot telnet to it:
telnet localhost ospfd-1
telnet: ospfd-1: bad port

telnet localhost ospfd-2
telnet: ospfd-2: bad port

Do you kown the reason ?

Regards,
Vinllen

**Comment by vinllen** [comment]
After i install the quagga, there is no quagga in /etc/init.d and /etc/. I have try to install the quagga in two hosts and all of them have the same question

I wonder whether i install the different branch which is "origin/cumulus-master" currently.

**Comment by ddutt** [comment]
Hi Vinllen,

The /etc/init.d/quagga part is in a debian subdir that we didn't export. Will do so later this week or early next week.

Dinesh

**Comment by vinllen** [comment]
OK, Thankyou Dinesh.

Do you have any HOWTO documents about muliti ospfd instance configuration?

I start the ospfd instance in the following command:
sudo ./ospfd -A 127.0.0.1 -n 1 -P 8876
sudo ./ospfd -A 127.0.0.1 -n 1 -P 8877

When i configure the ospf parameter :
ospfd(config)# router ospf 1
ospfd(config-router)# network 20.1.1.0/30 area 0
__The network command is not supported in multi-instance ospf__

So how to configure it ?
